-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: May 08, 2026 at 08:04 AM
-- Server version: 10.4.32-MariaDB
-- PHP Version: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `viuspot`
--

-- --------------------------------------------------------

--
-- Table structure for table `places`
--

CREATE TABLE `places` (
  `id` int(11) NOT NULL,
  `name` varchar(150) NOT NULL,
  `category_id` int(11) NOT NULL,
  `location` varchar(200) NOT NULL,
  `description` text DEFAULT NULL,
  `entrance_fee` decimal(10,2) DEFAULT 0.00,
  `parking_fee` decimal(10,2) DEFAULT 0.00,
  `meal_cost` decimal(10,2) DEFAULT 0.00,
  `facilities` text DEFAULT NULL COMMENT 'JSON array fasilitas, contoh: ["toilet","parkir","wifi","mushola"]',
  `latitude` varchar(20) DEFAULT NULL,
  `longitude` varchar(20) DEFAULT NULL,
  `image_url` varchar(255) DEFAULT '',
  `status` enum('pending','approved','rejected') DEFAULT 'pending',
  `submitted_by` int(11) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `places`
--

INSERT INTO `places` (`id`, `name`, `category_id`, `location`, `description`, `entrance_fee`, `parking_fee`, `meal_cost`, `facilities`, `latitude`, `longitude`, `image_url`, `status`, `submitted_by`, `created_at`, `updated_at`) VALUES
(1, 'Gunung Merbabu', 1, 'Magelang, Jawa Tengah', 'Gunung Merbabu adalah gunung berapi stratovolkano yang menjulang setinggi 3.145 mdpl di perbatasan Kabupaten Magelang, Boyolali, dan Semarang. Gunung ini terkenal dengan padang sabana yang luas dan menakjubkan, hamparan bunga edelweis yang harum, serta panorama matahari terbit yang spektakuler dari puncak Kenteng Songo. Terdapat beberapa jalur pendakian populer: Jalur Selo, Jalur Cunthel, dan Jalur Suwanting, masing-masing menawarkan karakteristik medan yang berbeda. Di puncak, pendaki bisa menyaksikan siluet Gunung Merapi, Sumbing, Sindoro, dan Lawu sekaligus. Sabana berlapis-lapis yang membentang di ketinggian 2.800 mdpl menjadi spot favorit foto dan kemah. Pendakian terbaik dilakukan pada musim kemarau (April–Oktober) saat trek kering dan pemandangan langit cerah.', 27000.00, 15000.00, 40000.00, '[\"toilet\",\"parkir\",\"warung\",\"camping ground\",\"pos pendakian\",\"air bersih\"]', '-7.4531', '110.4394', 'merbabu.jpg', 'approved', NULL, '2026-05-07 06:59:45', '2026-05-08 05:55:55'),
(2, 'Gunung Prau', 1, 'Dieng, Jawa Tengah', 'Gunung Prau setinggi 2.565 mdpl adalah surga tersembunyi di kawasan Dataran Tinggi Dieng, Kabupaten Wonosobo dan Batang. Puncaknya dikelilingi padang sabana yang konon terluas di Jawa Tengah, menjadikannya lokasi glamping dan kemping favorit di kalangan milenial. Fenomena \"lautan awan\" di pagi hari dan langit berbintang tanpa polusi cahaya di malam hari adalah daya tarik utamanya. Dari puncak, pendaki dapat menyaksikan panorama 360 derajat meliputi Gunung Sindoro, Sumbing, Merapi, Merbabu, Ungaran, dan Slamet secara bersamaan. Jalur pendakian via Patak Banteng adalah yang paling populer karena jarak tempuh relatif singkat (±4 jam). Aktivitas terbaik adalah bermalam untuk menikmati golden hour pagi dan sunset sore hari.', 20000.00, 10000.00, 35000.00, '[\"toilet\",\"parkir\",\"warung\",\"camping ground\",\"pos pendakian\",\"penyewaan tenda\",\"air bersih\"]', '-7.1911', '109.9072', 'prau.png', 'approved', NULL, '2026-05-07 06:59:45', '2026-05-08 05:56:21'),
(3, 'Cartenz Piramid', 1, 'Papua Pegunungan', 'Carstensz Pyramid atau Puncak Jaya adalah puncak tertinggi di Indonesia sekaligus puncak tertinggi di antara tujuh puncak beneng (Seven Summits) yang terletak di Benua Australia–Oceania, menjulang di ketinggian 4.884 mdpl. Berlokasi di jantung Pegunungan Sudirman, Papua Pegunungan, gunung ini ditutup lapisan gletser abadi yang kian menyusut akibat perubahan iklim. Pendakiannya dikategorikan sebagai salah satu yang paling teknis di dunia, membutuhkan keahlian panjat tebing, peralatan alpinisme lengkap, serta fisik dan mental yang prima. Izin pendakian harus diajukan jauh-jauh hari melalui prosedur administratif ketat. Pemandangan gletser tropis yang tersisa, ekosistem alpine unik, dan pengalaman mendaki di tanah Papua yang sakral menjadikan Carstensz sebagai impian setiap alpinis sejati Indonesia.', 2500000.00, 0.00, 150000.00, '[\"helipad\",\"porter\",\"pemandu wajib\",\"basecamp\"]', '-4.0789', '137.1583', 'cartenz.jpg', 'approved', NULL, '2026-05-07 06:59:45', '2026-05-08 05:56:49'),
(4, 'Pantai Ngetun', 1, 'Gunung Kidul, Yogyakarta', 'Pantai Ngetun adalah surga tersembunyi di ujung Kabupaten Gunungkidul, Yogyakarta, yang belum banyak terekspos secara masif. Pantai ini dikelilingi tebing-tebing karst megah khas pesisir selatan Jawa yang membentuk laguna alami dengan air berwarna biru kehijauan jernih. Akses menuju pantai melalui jalur trekking singkat melewati kebun warga yang asri, menambah sensasi petualangan. Ombak di teluk kecil ini relatif tenang sehingga aman untuk berenang dan snorkeling. Saat air surut, kawasan karang dangkal mengungkap berbagai biota laut yang menarik. Pantai ini buka hingga sore hari dan belum dipungut biaya pengelolaan besar, sehingga ideal bagi wisatawan yang mencari ketenangan jauh dari keramaian pantai utama seperti Baron atau Parangtritis.', 10000.00, 5000.00, 30000.00, '[\"toilet\",\"parkir\",\"warung\",\"area foto\"]', '-8.1345', '110.5678', 'ngetun.jpg', 'approved', NULL, '2026-05-07 06:59:45', '2026-05-08 05:57:07'),
(5, 'Gunung Bromo', 1, 'Probolinggo, Jawa Timur', 'Gunung Bromo (2.329 mdpl) adalah gunung berapi aktif paling ikonik di Indonesia, bagian dari Taman Nasional Bromo Tengger Semeru. Terletak di tengah lautan pasir luas bernama Segara Wedi seluas 10 km², kawah Bromo terus mengepulkan asap sulfur setiap saat. Ritual Yadnya Kasada yang dirayakan masyarakat Tengger setiap tahun menambah nilai budaya yang luar biasa. Titik matahari terbit terbaik adalah dari Bukit Pananjakan dan Bukit Kingkong. Untuk mencapai kawah, pengunjung dapat menyewa jeep 4WD dari Probolinggo/Malang, menaiki kuda, atau berjalan kaki melintasi lautan pasir. Pemandangan \"lautan pasir dan pagi bersalju\" yang melegenda telah menjadikan Bromo sebagai destinasi bucket-list nomor satu di Jawa Timur dan salah satu ikon pariwisata Indonesia di kancah internasional.', 35000.00, 30000.00, 50000.00, '[\"toilet\",\"parkir\",\"restoran\",\"mushola\",\"souvenir\",\"pemandu\",\"jeep_rental\",\"penyewaan_kuda\"]', '-7.9425', '112.9530', 'bromo.jpg', 'approved', NULL, '2026-05-07 06:59:45', '2026-05-08 04:23:14'),
(6, 'Desa Penglipuran', 2, 'Bangli, Bali', 'Desa Penglipuran di Kabupaten Bangli, Bali, telah memenangkan berbagai penghargaan sebagai salah satu desa terbersih dan terbaik di dunia. Desa adat ini mempertahankan tata ruang tradisional Bali Aga yang konsisten: satu jalan utama lurus diapit deretan pekarangan rumah bertembok dengan pintu masuk (angkul-angkul) seragam. Mobil dan motor dilarang masuk, menjaga kedamaian dan keasrian. Bambu menjadi tanaman dominan di sekeliling desa, membentuk hutan bambu yang nyaman dijelajahi. Warga masih menjalankan adat dan ritual Hindu Bali sehari-hari, sehingga pengunjung bisa menyaksikan kehidupan otentik. Tersedia homestay untuk menginap, serta warung khas penjual loloh cemcem (minuman herbal lokal) dan jajanan Bali. Waktu terbaik berkunjung adalah pagi hari sebelum rombongan wisata datang.', 30000.00, 5000.00, 35000.00, '[\"toilet\",\"parkir\",\"souvenir\",\"warung\",\"area foto\",\"homestay\",\"mushola\"]', '-8.4238', '115.3564', 'panglipuran.jpg', 'approved', NULL, '2026-05-07 06:59:45', '2026-05-08 05:57:24'),
(7, 'Tana Toraja', 2, 'Sulawesi Selatan', 'Tana Toraja di Sulawesi Selatan adalah salah satu destinasi budaya paling memukau di Asia Tenggara. Masyarakat Toraja terkenal dengan upacara pemakaman mewah bernama Rambu Solo — pesta kematian yang bisa berlangsung berhari-hari dengan menyembelih puluhan kerbau dan babi sebagai simbol penghormatan kepada almarhum. Jenazah disimpan di tebing batu (liang) yang dihiasi patung tau-tau (representasi orang meninggal). Rumah adat Tongkonan dengan atap melengkung berbentuk perahu adalah landmark arsitektur yang tak tertandingi. Kawasan pegunungan Toraja menawarkan trek melalui desa-desa tradisional, sawah bertingkat, dan pemandangan alam hijau yang dramatis. Kete Kesu, Londa, dan Bori adalah situs yang wajib dikunjungi. Festival Lovely December rutin menarik ribuan wisatawan mancanegara setiap tahunnya.', 60000.00, 20000.00, 50000.00, '[\"toilet\",\"parkir\",\"restoran\",\"souvenir\",\"pemandu\",\"homestay\",\"mushola\"]', '-3.0672', '119.8230', 'toraja.jpg', 'approved', NULL, '2026-05-07 06:59:45', '2026-05-08 04:23:14'),
(8, 'Desa Sade', 2, 'Lombok, NTB', 'Desa Sade adalah enclave budaya Suku Sasak di Lombok Tengah yang masih menjaga kemurnian tradisi leluhur. Rumah-rumah panggung beratap ilalang (bumbung) berderet rapi, lantainya dilapisi tanah liat campur kotoran kerbau yang dipercaya mengusir serangga — tradisi yang terus dijalankan hingga sekarang. Sekitar 700 warga Desa Sade hidup dari bertani dan menenun kain songket serta kain tenun khas Lombok yang dijual langsung kepada wisatawan. Pengunjung bisa belajar menenun, mengenakan pakaian adat, dan menyaksikan tari tradisional Sasak. Pemandu lokal (biasanya pemuda desa) siap menjelaskan filosofi hidup, adat pernikahan sorong serah aji krama, dan sejarah desa dalam bahasa Indonesia yang ramah. Desa ini buka setiap hari dan tidak ada tiket resmi, namun pemberian donasi sukarela sangat diapresiasi.', 0.00, 5000.00, 25000.00, '[\"toilet\",\"parkir\",\"souvenir\",\"pemandu\",\"warung\"]', '-8.8945', '116.2876', 'sade.jpg', 'approved', NULL, '2026-05-07 06:59:45', '2026-05-08 04:23:14'),
(9, 'Tari Kecak Uluwatu', 2, 'Badung, Bali', 'Pertunjukan Tari Kecak di Pura Uluwatu, Badung, Bali adalah salah satu pengalaman seni pertunjukan paling dramatis di dunia. Ribuan suara \"cak\" bergema dari ratusan penari lelaki berpakaian kotak-kotak hitam-putih yang membentuk lingkaran konsentris, melakonkan kisah Ramayana — penculikan Dewi Sita, pertempuran Rama melawan Rahwana, dan kemenangan kebaikan atas kejahatan. Pertunjukan berlangsung sore menjelang matahari terbenam di tepi tebing setinggi 70 meter, dengan laut biru Samudera Hindia sebagai latar belakang. Efek dramatisasi api lilin yang menyala saat momen klimaks menciptakan suasana magis. Pura Uluwatu sendiri adalah salah satu pura \"Kayangan Jagat\" (pura pelindung Bali) yang menjulang di tepi tebing dan dihuni kawanan kera. Datanglah 30 menit sebelum pertunjukan untuk memilih tempat duduk terbaik.', 150000.00, 20000.00, 60000.00, '[\"toilet\",\"parkir\",\"restoran\",\"souvenir\",\"area foto\",\"aksesibilitas\"]', '-8.8291', '115.0849', 'uluwatu.jpg', 'approved', NULL, '2026-05-07 06:59:45', '2026-05-08 05:57:43'),
(10, 'Desa Waerebo', 2, 'Manggarai, NTT', 'Desa Waerebo adalah desa tradisional paling terpencil dan paling magis di Flores, NTT, yang hanya bisa dijangkau dengan trekking 3–4 jam dari Desa Denge. Terletak di ketinggian 1.200 mdpl di dalam lembah hijau yang dikelilingi hutan tropis lebat, Waerebo dihuni komunitas Manggarai yang telah menjaga tujuh rumah adat Mbaru Niang mereka selama ratusan tahun. Mbaru Niang adalah rumah kerucut beratap jerami yang menjulang lima tingkat, masing-masing tingkat memiliki fungsi berbeda: hunian, penyimpanan makanan, benih, bekal darurat, dan persembahan. UNESCO mengakui Waerebo sebagai salah satu situs warisan arsitektur vernakular Asia Pasifik. Pengunjung wajib didampingi pemandu, melakukan ritual penyambutan adat (compang), dan bisa menginap semalam untuk merasakan kehidupan komunitas serta pemandangan kabut pagi yang tak terlupakan.', 50000.00, 0.00, 40000.00, '[\"toilet\",\"pemandu wajib\",\"warung\",\"homestay\",\"camping area\"]', '-8.7380', '120.5260', 'werebo.jpg', 'approved', NULL, '2026-05-07 06:59:45', '2026-05-08 05:55:30'),
(11, 'Candi Borobudur', 3, 'Magelang, Jawa Tengah', 'Candi Borobudur adalah mahakarya arsitektur Buddha terbesar di dunia yang dibangun pada abad ke-8 dan ke-9 Masehi oleh Dinasti Syailendra. Kompleks candi ini terdiri dari sembilan teras batu andesit yang tersusun dalam tiga zona kosmis: Kamadhatu (dunia hasrat), Rupadhatu (dunia bentuk), dan Arupadhatu (dunia tanpa bentuk) yang disimbolkan oleh 72 stupa berlubang dengan patung Buddha di dalamnya, serta stupa induk raksasa di puncak. Total relief yang terpahat sepanjang 2,5 km menceritakan kisah kehidupan Buddha dan ajaran kosmologi Buddha. Matahari terbit di Borobudur, saat siluet stupa-stupa terbalut kabut dengan latar belakang Gunung Merapi dan Merbabu, adalah salah satu pemandangan paling ikonik di Asia. Tersedia paket \"Borobudur Sunrise\" dengan akses eksklusif sebelum jam buka umum. UNESCO menetapkan Borobudur sebagai Warisan Budaya Dunia sejak 1991.', 52000.00, 20000.00, 40000.00, '[\"toilet\",\"parkir\",\"souvenir\",\"pemandu\",\"restoran\",\"aksesibilitas\",\"wifi\",\"area foto\"]', '-7.6079', '110.2038', 'borobudur.jpg', 'approved', NULL, '2026-05-07 06:59:45', '2026-05-08 06:00:33'),
(12, 'Kota Tua Jakarta', 3, 'Jakarta Barat, DKI Jakarta', 'Kawasan Kota Tua Jakarta atau Batavia Lama adalah pusat kota dagang VOC Belanda yang dibangun sejak abad ke-17. Area seluas ±1,3 km² ini menyimpan ratusan bangunan bergaya neo-klasik dan Art Deco Eropa yang masih berdiri megah. Museum Fatahillah (Museum Sejarah Jakarta) berdiri di bekas Balai Kota Batavia dengan koleksi artefak masa kolonial yang lengkap. Di sekeliling alun-alun, pengunjung bisa menyewa sepeda onthel berbagai warna untuk berkeliling dengan nuansa vintage yang instagrammable. Kafe-kafe bergaya retro banyak bermunculan di ruko-ruko tua yang direnovasi. Malam hari kawasan ini hidup dengan pertunjukan seni jalanan, street food, dan pertunjukan komunitas. Kota Tua terus dikembangkan sebagai kawasan heritage modern yang memadukan sejarah dan kreativitas kota.', 0.00, 20000.00, 55000.00, '[\"toilet\",\"parkir\",\"restoran\",\"souvenir\",\"area foto\",\"aksesibilitas\",\"wifi\",\"sepeda sewa\"]', '-6.1376', '106.8171', 'kotatua.jpg', 'approved', NULL, '2026-05-07 06:59:45', '2026-05-08 05:59:00'),
(13, 'Lawang Sewu', 3, 'Semarang, Jawa Tengah', 'Lawang Sewu (secara harfiah: Seribu Pintu) adalah bangunan monumental warisan kolonial Belanda yang dibangun tahun 1904–1919 sebagai kantor pusat Nederlandsch-Indische Spoorweg Maatschappij (NIS), perusahaan kereta api swasta. Terletak di jantung Kota Semarang, gedung tiga lantai ini terkenal dengan deretan pintu dan jendela kaca berwarna-warni yang jumlahnya ribuan, menciptakan permainan cahaya yang menakjubkan. Basement Lawang Sewu menyimpan sejarah kelam sebagai tempat penahanan dan eksekusi pada masa pendudukan Jepang. Kini gedung ini telah direstorasi dan dikelola PT. KAI sebagai museum dan cagar budaya. Pengunjung bisa mengikuti tur malam bertema \"misteri\" yang populer, atau tur siang yang mengupas sejarah arsitektur dan perkeretaapian. Relief dan ornamen eksteriornya merupakan contoh arsitektur Art Nouveau terbaik di Indonesia.', 15000.00, 10000.00, 40000.00, '[\"toilet\",\"parkir\",\"souvenir\",\"pemandu\",\"area foto\",\"aksesibilitas\"]', '-6.9840', '110.4105', 'lawangsewu.jpg', 'approved', NULL, '2026-05-07 06:59:45', '2026-05-08 06:01:00'),
(14, 'Benteng Vredeburg', 3, 'Yogyakarta, DI Yogyakarta', 'Benteng Vredeburg dibangun oleh pemerintah kolonial VOC tahun 1760 atas permintaan Sri Sultan Hamengku Buwono I sebagai \"jaminan keamanan\" — meski sesungguhnya berfungsi mengawasi Keraton Yogyakarta dari jarak dekat. Berlokasi tepat di ujung Jalan Malioboro berhadapan dengan Gedung Agung (Istana Presiden), benteng berbentuk segi empat dengan bastion di setiap sudutnya ini kini menjadi Museum Perjuangan. Diorama-diorama di dalam museum menceritakan perjalanan perjuangan bangsa Indonesia dari masa penjajahan hingga kemerdekaan secara kronologis dan detail. Bagi peminat sejarah, museum ini adalah referensi visual terlengkap tentang revolusi kemerdekaan Indonesia. Halaman benteng yang luas juga menjadi venue rutin berbagai festival seni dan budaya Yogyakarta sepanjang tahun. Tiket masuknya sangat terjangkau, menjadikannya destinasi edukasi favorit keluarga.', 3000.00, 5000.00, 35000.00, '[\"toilet\",\"parkir\",\"souvenir\",\"pemandu\",\"area foto\",\"aksesibilitas\",\"mushola\"]', '-7.8003', '110.3665', 'vredeburg.jpg', 'approved', NULL, '2026-05-07 06:59:45', '2026-05-08 06:01:21'),
(15, 'Istana Maimun', 3, 'Medan, Sumatera Utara', 'Istana Maimun adalah istana Kesultanan Deli yang dibangun pada 1888 atas prakarsa Sultan Makmun Al Rasyid Perkasa Alamsyah. Istana ini merupakan perpaduan arsitektur Melayu, Islam, Spanyol, Italia, dan India — cerminan jaringan perdagangan dan diplomasi Kesultanan Deli yang kosmopolit pada zamannya. Bangunan utama berwarna kuning (warna khas Melayu) dengan kubah-kubah berbentuk bawang dan ornamen bintang segi delapan. Mahkota Deli, senjata, dan perlengkapan kerajaan dipajang di ruang utama yang masih digunakan untuk upacara adat. Sultan dan keluarga kerajaan masih tinggal di sebagian sayap istana. Di halaman terdapat meriam Puntung yang dikeramatkan dengan legenda Putri Hijau. Mengenakan baju kurung atau kebaya untuk berfoto di depan istana adalah aktivitas favorit wisatawan yang berkunjung ke Medan.', 10000.00, 5000.00, 45000.00, '[\"toilet\",\"parkir\",\"souvenir\",\"pemandu\",\"area foto\",\"mushola\"]', '3.5753', '98.6835', 'maimun.jpg', 'approved', NULL, '2026-05-07 06:59:45', '2026-05-08 06:01:39'),
(16, 'Masjid Istiqlal', 4, 'Jakarta Pusat, DKI Jakarta', 'Masjid Istiqlal adalah masjid terbesar di Asia Tenggara dan salah satu yang terbesar di dunia, mampu menampung hingga 200.000 jamaah. Dibangun pada 1961–1978 dengan desain arsitek nasionalis Friedrich Silaban, Istiqlal mengusung arsitektur modern minimalis yang mencerminkan kemerdekaan dan persatuan (istiqlal = kemerdekaan dalam bahasa Arab). Kubah utama berdiameter 45 meter disimbolkan tahun kemerdekaan Indonesia. Lima menara setinggi 66,66 meter melambangkan panjang ayat Al-Quran. Posisinya yang berhadapan langsung dengan Gereja Katedral Jakarta menjadi simbol kerukunan beragama yang kuat. Masjid ini terbuka untuk wisatawan non-Muslim dengan dress code tertutup dan panduan tur tersedia. Suasana salat Jumat dan Idul Fitri di Istiqlal adalah pengalaman spiritual dan sosial yang tak terlupakan.', 0.00, 5000.00, 40000.00, '[\"toilet\",\"parkir\",\"mushola\",\"aksesibilitas\",\"area_foto\",\"pemandu\"]', '-6.1702', '106.8310', 'istiqlal.jpg', 'approved', NULL, '2026-05-07 06:59:45', '2026-05-08 04:23:14'),
(17, 'Pura Besakih', 4, 'Karangasem, Bali', 'Pura induk terbesar dan paling suci di Bali, berlokasi di lereng Gunung Agung.', 60000.00, 10000.00, 40000.00, '[\"toilet\",\"parkir\",\"souvenir\",\"pemandu\",\"restoran\",\"mushola\",\"area_foto\"]', '-8.3739', '115.4567', 'besakih.jpg', 'approved', NULL, '2026-05-07 06:59:45', '2026-05-08 04:23:14'),
(18, 'Gereja Blenduk', 4, 'Semarang, Jawa Tengah', 'Gereja protestan bersejarah dengan kubah tembaga ikonik di Kota Lama.', 0.00, 10000.00, 35000.00, '[\"toilet\",\"parkir\",\"area foto\",\"pemandu\"]', '-6.9682', '110.4275', 'blenduk.jpg', 'approved', NULL, '2026-05-07 06:59:45', '2026-05-08 05:58:16'),
(19, 'Makam Sunan Kalijaga', 4, 'Demak, Jawa Tengah', 'Makam wali songo dengan sejarah Islam yang dalam dan arsitektur tradisional.', 0.00, 5000.00, 25000.00, '[\"toilet\",\"parkir\",\"souvenir\",\"mushola\",\"warung\"]', '-6.8940', '110.6370', 'makamsunan.jpg', 'approved', NULL, '2026-05-07 06:59:45', '2026-05-08 04:23:14'),
(20, 'Vihara Dhanagun', 4, 'Bogor, Jawa Barat', 'Vihara tertua dan terbesar di Bogor dengan patung Buddha raksasa.', 0.00, 5000.00, 30000.00, '[\"toilet\",\"parkir\",\"souvenir\",\"mushola\",\"area foto\"]', '-6.5950', '106.7896', 'vihara.jpg', 'approved', NULL, '2026-05-07 06:59:45', '2026-05-08 05:58:00'),
(21, 'Malioboro', 5, 'Yogyakarta, DI Yogyakarta', 'Malioboro adalah jantung wisata Kota Yogyakarta, sebuah koridor sepanjang ±1 km yang memadukan sejarah, budaya, kuliner, dan belanja dalam satu napas. Nama Malioboro dipercaya berasal dari nama Duke of Marlborough atau dari kata Sansekerta \"malyabhara\" (dihiasi bunga). Deretan pedagang kaki lima menjajakan batik, wayang kulit, perak, blangkon, dan berbagai kerajinan khas Jogja di sepanjang trotoar yang telah diperlebar dan diperindah. Malam hari, angkringan menjadi simbol kesetaraan sosial Yogyakarta — dari mahasiswa hingga pejabat duduk bersila menikmati nasi kucing, wedang jahe, dan berbagai lauk sederhana dengan harga sangat terjangkau. Kawasan ini juga merupakan koridor budaya menuju Keraton Yogyakarta dan Alun-Alun Utara. Street art, musisi jalanan berbakat, dan becak kayuh listrik melengkapi pengalaman berjalan-jalan di Malioboro yang sesungguhnya tak pernah tidur.', 0.00, 15000.00, 60000.00, '[\"toilet\",\"parkir\",\"restoran\",\"souvenir\",\"pemandu\",\"angkringan\",\"atm\",\"wifi\",\"aksesibilitas\"]', '-7.7930', '110.3658', 'malioboro.jpg', 'approved', NULL, '2026-05-07 06:59:45', '2026-05-08 04:23:14'),
(22, 'Pasar Cihapit', 5, 'Bandung, Jawa Barat', 'Pasar Cihapit di Kecamatan Cibeunying Kaler, Bandung, adalah pasar basah tradisional yang terkenal sebagai surga kuliner kaki lima autentik Sunda sejak era kolonial. Di sini berjejer warung-warung yang menjajakan nasi timbel, batagor, siomay, colenak, surabi, karedok, peuyeum, dan aneka jajanan Sunda lainnya dengan harga yang sangat merakyat. Kesegaran bahan baku langsung dari pasar membuat cita rasa masakan terasa sangat autentik. Suasana pasar yang hidup, interaksi hangat pedagang dan pembeli, serta aroma rempah yang khas menciptakan pengalaman kuliner yang jauh dari kesan komersialisasi. Pasar ini paling ramai pada pagi hari (06.00–10.00 WIB), cocok untuk sarapan pagi yang berkesan bagi wisatawan yang ingin merasakan keseharian warga Bandung.', 0.00, 0.00, 40000.00, '[\"toilet\",\"warung\",\"area foto\"]', '-6.9034', '107.6201', 'chiapit.jpg', 'approved', NULL, '2026-05-07 06:59:45', '2026-05-08 05:59:56'),
(23, 'Jalan Sabang', 5, 'Jakarta Pusat, DKI Jakarta', 'Kawasan Jalan Sabang (H. Agus Salim) di Jakarta Pusat adalah destinasi kuliner malam yang legendaris dan lintas generasi. Ratusan warung tenda berjejer menyajikan menu nusantara yang lengkap: sate Madura, nasi goreng Kambing Kebon Sirih, soto Betawi, gulai, bakso, mie ayam, es cendol, dan masih banyak lagi. Lokasi strategis di pusat kota menjadikannya titik kumpul favorit pegawai kantoran, keluarga, hingga wisatawan mancanegara yang ingin merasakan street food Jakarta. Beberapa warung telah beroperasi sejak puluhan tahun dan diwariskan lintas generasi, mempertahankan resep otentik. Aktivitas terbaik adalah datang dalam rombongan, memesan berbagai menu dari warung berbeda, dan menikmati makan malam sambil merasakan denyut nadi kota Jakarta yang kosmopolit.', 0.00, 15000.00, 55000.00, '[\"toilet\",\"parkir\",\"restoran\",\"area foto\",\"atm\"]', '-6.1850', '106.8320', 'sabang.jpg', 'approved', NULL, '2026-05-07 06:59:45', '2026-05-08 05:59:39'),
(24, 'Kya-Kya Surabaya', 5, 'Surabaya, Jawa Timur', 'Kawasan wisata kuliner Chinatown dengan makanan Tionghoa autentik.', 0.00, 10000.00, 50000.00, '[\"toilet\",\"parkir\",\"restoran\",\"area foto\",\"atm\"]', '-7.2370', '112.7378', 'kyakya.jpg', 'approved', NULL, '2026-05-07 06:59:45', '2026-05-08 05:59:24'),
(25, 'Simpang Lima Semarang', 5, 'Semarang, Jawa Tengah', 'Alun-alun kota dengan food court, kuliner malam, and pemandangan urban.', 0.00, 5000.00, 45000.00, '[\"toilet\",\"parkir\",\"restoran\",\"souvenir\",\"area foto\",\"wifi\",\"aksesibilitas\"]', '-6.9845', '110.4108', 'simpangsemarang.jpg', 'approved', NULL, '2026-05-07 06:59:45', '2026-05-08 05:59:13'),
(26, 'Dufan Ancol', 6, 'Jakarta Utara, DKI Jakarta', 'Taman hiburan terbesar di Indonesia dengan wahana ekstrem dan edukasi.', 300000.00, 25000.00, 100000.00, '[\"toilet\",\"parkir\",\"restoran\",\"souvenir\",\"area_foto\",\"wifi\",\"aksesibilitas\",\"mushola\",\"atm\",\"loker\"]', '-6.1256', '106.8382', 'dufan.jpg', 'approved', NULL, '2026-05-07 06:59:45', '2026-05-08 04:23:14'),
(27, 'Jatim Park', 6, 'Batu, Jawa Timur', 'Kompleks wisata edutainment dengan wahana modern dan museum unik.', 160000.00, 20000.00, 80000.00, '[\"toilet\",\"parkir\",\"restoran\",\"souvenir\",\"area_foto\",\"wifi\",\"aksesibilitas\",\"mushola\",\"atm\"]', '-7.8806', '112.5246', 'jpark.jpg', 'approved', NULL, '2026-05-07 06:59:45', '2026-05-08 04:23:14'),
(28, 'Trans Studio', 6, 'Makassar, Sulawesi Selatan', 'Indoor theme park terbesar dengan wahana berteknologi tinggi.', 200000.00, 15000.00, 70000.00, '[\"toilet\",\"parkir\",\"restoran\",\"souvenir\",\"area_foto\",\"wifi\",\"aksesibilitas\",\"mushola\",\"atm\"]', '-5.1584', '119.4128', 'trans.jpg', 'approved', NULL, '2026-05-07 06:59:45', '2026-05-08 04:23:14'),
(29, 'Waterbom Bali', 6, 'Kuta, Bali', 'Taman air terbaik di Asia dengan seluncuran spektakuler.', 530000.00, 0.00, 120000.00, '[\"toilet\",\"parkir\",\"restoran\",\"loker\",\"area_foto\",\"wifi\",\"aksesibilitas\",\"atm\",\"lounge\"]', '-8.7610', '115.1690', 'waterboom.jpg', 'approved', NULL, '2026-05-07 06:59:45', '2026-05-08 04:23:14'),
(30, 'Saloka Park', 6, 'Semarang, Jawa Tengah', 'Theme park dengan nuansa lokal Jawa and wahana keluarga.', 150000.00, 15000.00, 60000.00, '[\"toilet\",\"parkir\",\"restoran\",\"souvenir\",\"area_foto\",\"wifi\",\"aksesibilitas\",\"mushola\",\"atm\"]', '-7.2820', '110.4778', 'saloka.jpg', 'approved', NULL, '2026-05-07 06:59:45', '2026-05-08 04:23:14'),
(31, 'Museum Geologi', 7, 'Bandung, Jawa Barat', 'Museum geologi lengkap dengan fosil, meteorit, and informasi vulkanologi.', 3000.00, 5000.00, 35000.00, '[\"toilet\",\"parkir\",\"souvenir\",\"pemandu\",\"area_foto\",\"aksesibilitas\",\"mushola\"]', '-6.9007', '107.6215', 'geologi.jpg', 'approved', NULL, '2026-05-07 06:59:45', '2026-05-08 04:23:14'),
(32, 'Taman Pintar', 7, 'Yogyakarta, DI Yogyakarta', 'Pusat edukasi interaktif untuk anak and keluarga dengan science center.', 10000.00, 10000.00, 35000.00, '[\"toilet\",\"parkir\",\"restoran\",\"souvenir\",\"area_foto\",\"wifi\",\"aksesibilitas\",\"mushola\",\"atm\"]', '-7.8005', '110.3689', 'tamanpintar.jpg', 'approved', NULL, '2026-05-07 06:59:45', '2026-05-08 04:23:14'),
(33, 'Seaworld Ancol', 7, 'Jakarta Utara, DKI Jakarta', 'Akuarium laut terbesar dengan terowongan bawah air and pertunjukan ikan.', 120000.00, 25000.00, 65000.00, '[\"toilet\",\"parkir\",\"restoran\",\"souvenir\",\"area_foto\",\"wifi\",\"aksesibilitas\",\"mushola\",\"atm\"]', '-6.1262', '106.8361', 'seaworld.jpg', 'approved', NULL, '2026-05-07 06:59:45', '2026-05-08 04:23:14'),
(34, 'Museum MACAN', 7, 'Jakarta Barat, DKI Jakarta', 'Museum seni modern and kontemporer dengan koleksi internasional.', 150000.00, 10000.00, 60000.00, '[\"toilet\",\"parkir\",\"restoran\",\"souvenir\",\"area_foto\",\"wifi\",\"aksesibilitas\",\"atm\"]', '-6.1767', '106.7896', 'mmacan.jpg', 'approved', NULL, '2026-05-07 06:59:45', '2026-05-08 04:23:14'),
(35, 'Ragunan', 7, 'Jakarta Selatan, DKI Jakarta', 'Kebun binatang terluas di Indonesia dengan koleksi fauna nusantara.', 4000.00, 15000.00, 40000.00, '[\"toilet\",\"parkir\",\"restoran\",\"souvenir\",\"area_foto\",\"aksesibilitas\",\"mushola\",\"atm\"]', '-6.3046', '106.8201', 'ragunan.jpg', 'approved', NULL, '2026-05-07 06:59:45', '2026-05-08 04:23:14'),
(36, 'Pasar Beringharjo', 8, 'Yogyakarta, DI Yogyakarta', 'Pasar tradisional legendaris dengan batik, makanan, and oleh-oleh khas.', 0.00, 10000.00, 35000.00, '[\"toilet\",\"parkir\",\"souvenir\",\"warung\",\"area_foto\",\"aksesibilitas\",\"atm\"]', '-7.7988', '110.3671', 'beringharjo.jpg', 'approved', NULL, '2026-05-07 06:59:45', '2026-05-08 04:23:14'),
(37, 'Pasar Tanah Abang', 8, 'Jakarta Pusat, DKI Jakarta', 'Pasar grosir tekstil terbesar di Asia Tenggara dengan ribuan kios.', 0.00, 15000.00, 40000.00, '[\"toilet\",\"parkir\",\"souvenir\",\"restoran\",\"area_foto\",\"aksesibilitas\",\"atm\",\"mushola\"]', '-6.1856', '106.8108', 'tanahabang.jpg', 'approved', NULL, '2026-05-07 06:59:45', '2026-05-08 04:23:14'),
(38, 'Pasar Sukawati', 8, 'Gianyar, Bali', 'Pasar seni tradisional Bali with lukisan, patung, and kerajinan.', 0.00, 5000.00, 30000.00, '[\"toilet\",\"parkir\",\"souvenir\",\"warung\",\"area_foto\"]', '-8.6062', '115.2885', 'sukawati.jpg', 'approved', NULL, '2026-05-07 06:59:45', '2026-05-08 04:23:14'),
(39, 'Grand Indonesia', 8, 'Jakarta Pusat, DKI Jakarta', 'Mall premium dengan tenant internasional and entertainment center.', 0.00, 25000.00, 100000.00, '[\"toilet\",\"parkir\",\"restoran\",\"souvenir\",\"area_foto\",\"wifi\",\"aksesibilitas\",\"atm\",\"mushola\",\"bioskop\"]', '-6.1947', '106.8208', 'grand.jpg', 'approved', NULL, '2026-05-07 06:59:45', '2026-05-08 04:23:14'),
(40, 'Jalan Riau Bandung', 8, 'Bandung, Jawa Barat', 'Kawasan distro and fashion lokal dengan merek-merek kreatif Indonesia.', 0.00, 10000.00, 50000.00, '[\"toilet\",\"parkir\",\"restoran\",\"souvenir\",\"area_foto\",\"wifi\",\"atm\"]', '-6.9076', '107.6113', 'jalanriauband.jpg', 'approved', NULL, '2026-05-07 06:59:45', '2026-05-08 04:23:14');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `places`
--
ALTER TABLE `places`
  ADD PRIMARY KEY (`id`),
  ADD KEY `category_id` (`category_id`),
  ADD KEY `submitted_by` (`submitted_by`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `places`
--
ALTER TABLE `places`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=41;

--
-- Constraints for dumped tables
--

--
-- Constraints for table `places`
--
ALTER TABLE `places`
  ADD CONSTRAINT `places_ibfk_1` FOREIGN KEY (`category_id`) REFERENCES `categories` (`id`) ON DELETE CASCADE,
  ADD CONSTRAINT `places_ibfk_2` FOREIGN KEY (`submitted_by`) REFERENCES `users` (`id`) ON DELETE SET NULL;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
